void test();
int matrixfibo(int n);
void  nlimit(int limit, int *arr, int curr);
void  ndist(int limit, int *availablearr, int *prevchoice, int prevpointer, int availablelength);
long fibo(long a, int *arr);
int climb(int n, int k, int *arr);
void search(char grid[2][5], int rows, int cols, char*string);
int power(int n, int a);
void mergesortstart();
void  ndistrev(int limit, int *availablearr, int *prevchoice, int prevpointer, int availablelength, char* rev);